### ISSUE TITLE
You are already running that command block

### ISSUE THREAD

**Issue by SlimeDog** [PimvanderLoos/BigDoors#22]
Paper 1.20.2-201
BigDoors Alpha 0.1.8.48 (b1150)

When I right-click on a command button (via CommandSigns) to `toggledoor`, I get the title message in-game (not with left-click). There are no messages in the console/log, even with `DEBUG:true`.

When I run the same command `toggledoor` directly, the message does not appear (or, as noted above, if I left-click).

In both cases, the door is toggled correctly. CommandSigns has not changed, but perhaps this is a CommandSigns (or Paper click-handling) issue. The message did not occur in Paper 1.20.1 with BigDoors build 1143. Any ideas?

**Comment by PimvanderLoos** [comment]
Huh, I have no idea what could have changed to cause that. I didn't change any of the command handling code in any way.

[THESE](https://github.com/PimvanderLoos/BigDoors/compare/a301cb5...a22c87a) are the changes between 1143 and 1150. The significant ones are (mostly in the order of listed changed files):
1) Added a new NMS module for 1.20.2 for the falling block entities we use for animation.
2) Refactored update checker so we can reuse version comparison elsewhere (database, specifically).
3) Updated FakePlayerInstantiator to provide the new `ClientInformation` parameter as used by the `Player` class. (The one I did create initially but then forgot to actually use, leading to your issue about spamming `InvocationTargetException` :facepalm:)
4) Changed redstone handling so powerblocks respond to redstone blocks:
    - Being placed next to them (`BlockPlaceEvent`).
    - Being moved around by (sticky) pistons (`BlockPistonExtendEvent`, `BlockPistonRetractEvent`).
5) Updated the SQLite storage class because of the sudden removal of support for the `PreparedStatement#getGeneratedKeys()` method (the replacement of which wasn't introduced until 2021).

Out of all of these changes, only point 3 has anything to do with players and chat. However, the FakePlayerInstantiator is _only_ used to create fake 'online' player instances for players who are actually offline. Therefore, it shouldn't have any impact on the chat messages you receive. To be absolutely sure of this, you could try to disable all protection hooks in the config and try again, as without any protection hooks, the plugin will not create any fake players (which you can verify using the broken 1148 build.)

Other than that, I don't see how any of the changes between these builds could result in the issue you're describing. I'm 99.9% certain the BigDoors does not send any title messages by itself either.

**Comment by SlimeDog** [comment]
Thanks for the details. Note that the messages are in chat, not in titles.

Another plugin (or Spigot/Paper changes) must be the cause. I will try to isolate further.

**Comment by SlimeDog** [comment]
It looks like to problem is in `CommandSigns`. Sad.
